# -*- coding: utf-8 -*-
"""armonicos_cmb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XknBZQPVd0jILdf3MfJfG_f7DvGxqLl
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import sph_harm

# III. Armónicos esféricos para comparar multipolos bajos y altos

# malla angular.
# theta: ángulo polar, va de 0 a pi
# phi: ángulo azimutal, va de 0 a 2pi

theta = np.linspace(0, np.pi, 300)
phi = np.linspace(0, 2*np.pi, 600)

PHI, THETA = np.meshgrid(phi, theta)


def armonico_real(l, m):

    #Calcula la parte real del armónico esférico Y_l^m(theta, phi).
    #En scipy, sph_harm recibe los argumentos como sph_harm(m, l, phi, theta)

    Y_lm = sph_harm(m, l, PHI, THETA)
    return np.real(Y_lm)


def graficar_armonico(l, m, nombre_archivo, titulo):

    #Grafica la parte real del armónico esférico en una proyección rectangular.

    Z = armonico_real(l, m)

    plt.figure(figsize=(10, 5))

    mapa = plt.pcolormesh(
        PHI,
        THETA,
        Z,
        shading="auto",
        cmap="coolwarm"
    )

    plt.colorbar(mapa, label=r"$\mathrm{Re}(Y_{\ell m})$")

    plt.xlabel(r"$\phi$")
    plt.ylabel(r"$\theta$")
    plt.title(titulo)

    # En radianes
    plt.xticks(
        [0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi],
        [r"$0$", r"$\pi/2$", r"$\pi$", r"$3\pi/2$", r"$2\pi$"]
    )

    plt.yticks(
        [0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi],
        [r"$0$", r"$\pi/4$", r"$\pi/2$", r"$3\pi/4$", r"$\pi$"]
    )

    plt.tight_layout()
    plt.savefig(nombre_archivo, dpi=300, bbox_inches="tight")
    plt.show()



# Multipolo bajo

# l = 2 representa una estructura grande, tipo cuadrupolo.
graficar_armonico(
    l=2,
    m=0,
    nombre_archivo="armonico_bajo.png",
    titulo=r"Multipolo bajo: $\ell=2$, $m=0$"
)


# Multipolo alto

# l = 12 representa estructuras más pequeñas.
graficar_armonico(
    l=12,
    m=5,
    nombre_archivo="armonico_alto.png",
    titulo=r"Multipolo alto: $\ell=12$, $m=5$"
)