# -*- coding: utf-8 -*-
"""funciones_neumann

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWgSmKWHRpvbCVDN3zwo4brED1EL79G0
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.special import yv
from google.colab import files


# 2. Funciones de Neumann

# Se empieza en 0.01 porque las funciones de Neumann divergen en x = 0
x = np.linspace(0.01, 20, 2000)

# Funciones de Neumann N_0(x), N_1(x), N_2(x)
# En scipy se escriben como yv(n, x), porque también se conocen como Y_n(x)
N0 = yv(0, x)
N1 = yv(1, x)
N2 = yv(2, x)

# Gráfica
plt.figure(figsize=(10, 5))

plt.plot(x, N0, label=r"$N_0(x)$")
plt.plot(x, N1, label=r"$N_1(x)$")
plt.plot(x, N2, label=r"$N_2(x)$")

plt.axhline(0, linewidth=0.8)

plt.xlabel(r"$x$")
plt.ylabel(r"$N_n(x)$")
plt.title(r"Funciones de Neumann $N_0(x)$, $N_1(x)$ y $N_2(x)$")
plt.legend()
plt.grid(True, alpha=0.3)

# Para que se vea bien y no se deforme demasiado por la divergencia cerca de x=0
plt.ylim(-5, 2)

plt.tight_layout()
plt.savefig("funciones_neumann.png", dpi=300, bbox_inches="tight")
plt.show()


files.download("funciones_neumann.png")